
[package]
name = "LoganOS"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "LoganOS"
test = false
bench = false

[dependencies]
bootloader = "0.9"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
